data_params:
  num_workers: 12
  steps_per_epoch: 1000
  fold: 0
  activation: sigmoid
  folds_csv: tables/folds_v4.csv

  batch_size: 4
  augs: hsv_no_cutout_harder
  augs_params:
    crop_size: 1024

    pad_height: 1344
    pad_width: 1344



train_params:
  name: rn34_topology_FIXED_0
  model_name: selim_rn34_unet_dropout
  loss: LossMixture
  loss_params:
    focal_weight: 3.0
    dice_weight: 1.0
    topology_weight: 4.0
  metrics: [IoU]
  num_classes: 1
  checkpoint_saver:
    metric_name: loss
    mode: min
    num_checkpoints: 3
    save_optim: 0
  early_stopping:
    metric_name: loss
    mode: min



stages:
#  stage1:
#    freeze_encoder: 1
#    optimizer: Adam
#    optimizer_params:
#      lr: 0.0001
#    scheduler: ReduceLROnPlateau
#    scheduler_params:
#      patience: 00
#      factor: 0.1
#    epochs: 2
#    early_stopping:
#      patience: 2
#    data_params:
#      batch_size: 80
#      augs: hsv_no_cutout_harder
#      augs_params:
#        crop_size: 224
#
#        pad_height: 1344
#        pad_width: 1344

  stage2:
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 0
      factor: 0.1
    epochs: 10
    early_stopping:
      patience: 2
    data_params:
      batch_size: 70
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 224

        pad_height: 1344
        pad_width: 1344


  stage3:
    freeze_encoder: 1
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 0
      factor: 0.1
    epochs: 2
    early_stopping:
      patience: 1
    data_params:
      batch_size: 12
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 512

        pad_height: 1344
        pad_width: 1344

  stage4:
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 0
      factor: 0.1
    epochs: 10
    early_stopping:
      patience: 2
    data_params:
      batch_size: 12
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 512

        pad_height: 1344
        pad_width: 1344

  stage1:
    pass: pass


predict_params:
  test_csv: tables/test.csv
  batch_size: 4
  num_checkpoints: 1
  metric_mode: min
  part: []
  TTA: D4

