data_params:
  num_workers: 12
  steps_per_epoch: 300
  fold: 0
  activation: softmax
  folds_csv: tables/folds_v4.csv

  batch_size: 4
  augs: hsv_no_cutout_harder
  augs_params:
    crop_size: 1024

    pad_height: 1344
    pad_width: 1344



train_params:
  name: rn50_fpn_KLspeed_0
  model_name: rn50_fpn
  loss: SoftmaxKLDivLoss
  metrics: []
  num_classes: 7
  checkpoint_saver:
    metric_name: loss
    mode: min
    num_checkpoints: 3
    save_optim: 0
  early_stopping:
    metric_name: loss
    mode: min



stages:
  stage3:
    freeze_encoder: 1
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 0
      factor: 0.1
    epochs: 20
    early_stopping:
      patience: 1
    data_params:
      batch_size: 50
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 512

        pad_height: 1344
        pad_width: 1344

  stage4:
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 1
      factor: 0.5
    epochs: 100
    early_stopping:
      patience: 2
    data_params:
      batch_size: 24
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 512

        pad_height: 1344
        pad_width: 1344


predict_params:
  test_csv: tables/test.csv
  batch_size: 4
  num_checkpoints: 1
  metric_mode: min
  part: []
  TTA: D4

