data_params:
  num_workers: 24
  steps_per_epoch: 300
  fold: 0
  activation: sigmoid
  folds_csv: tables/folds_v4.csv

  batch_size: 4
  augs: hsv_no_cutout_harder
  augs_params:
    crop_size: 1024

    pad_height: 1344
    pad_width: 1344



train_params:
  name: rx101_FIXED_1
  model_name: selim_rx101_unet
  loss: LossMixture
  loss_params:
    focal_weight: 3.0
    dice_weight: 1.0
  metrics: [IoU]
  num_classes: 1
  checkpoint_saver:
    metric_name: loss
    mode: min
    num_checkpoints: 3
    save_optim: 0
  early_stopping:
    metric_name: loss
    mode: min



stages:
#  stage1:
#    freeze_encoder: 1
#    optimizer: Adam
#    optimizer_params:
#      lr: 0.0001
#    scheduler: ReduceLROnPlateau
#    scheduler_params:
#      patience: 1
#      factor: 0.1
#    epochs: 20
#    early_stopping:
#      patience: 3
#    data_params:
#      batch_size: 140
#      augs: hsv_no_cutout_harder
#      augs_params:
#        crop_size: 224
#
#        pad_height: 1344
#        pad_width: 1344

  stage2:
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 1
      factor: 0.5
    epochs: 100
    early_stopping:
      patience: 4
    data_params:
      batch_size: 80
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 224

        pad_height: 1344
        pad_width: 1344


  stage3:
    freeze_encoder: 1
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 1
      factor: 0.1
    epochs: 20
    early_stopping:
      patience: 3
    data_params:
      batch_size: 40
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 512

        pad_height: 1344
        pad_width: 1344

  stage4:
    optimizer: Adam
    optimizer_params:
      lr: 0.0001
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 1
      factor: 0.5
    epochs: 100
    early_stopping:
      patience: 4
    data_params:
      batch_size: 16
      augs: hsv_no_cutout_harder
      augs_params:
        crop_size: 512

        pad_height: 1344
        pad_width: 1344

  stage1:
    pass: pass



predict_params:
  test_csv: tables/test.csv
  batch_size: 4
  num_checkpoints: 1
  metric_mode: min
  part: []

